/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Ponto;
import Model.Quadrante;
import javax.swing.JOptionPane;

/**
 *
 * @author Laura Möller
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTX = new javax.swing.JTextField();
        jTY = new javax.swing.JTextField();
        btnAvaliar = new javax.swing.JButton();
        jCSegundo = new javax.swing.JCheckBox();
        jCEixoX = new javax.swing.JCheckBox();
        jCEixoY = new javax.swing.JCheckBox();
        jCPrimeiro = new javax.swing.JCheckBox();
        jCTerceiro = new javax.swing.JCheckBox();
        jCQuarto = new javax.swing.JCheckBox();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Eixo X:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Eixo Y:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Posição:");

        btnAvaliar.setText("Avaliar");
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });

        jCSegundo.setText("No 2º Quadrante");
        jCSegundo.setEnabled(false);
        jCSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSegundoActionPerformed(evt);
            }
        });

        jCEixoX.setText("Incide sobre o Eixo X");
        jCEixoX.setEnabled(false);

        jCEixoY.setText("Incide sobre o Eixo Y");
        jCEixoY.setEnabled(false);

        jCPrimeiro.setText("No 1º Quadrante");
        jCPrimeiro.setEnabled(false);
        jCPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPrimeiroActionPerformed(evt);
            }
        });

        jCTerceiro.setText("No 3º Quadrante");
        jCTerceiro.setEnabled(false);
        jCTerceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTerceiroActionPerformed(evt);
            }
        });

        jCQuarto.setText("No 4º Quadrante");
        jCQuarto.setEnabled(false);
        jCQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCQuartoActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvaliar)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTX)
                                    .addComponent(jTY)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCEixoX)
                            .addComponent(jCEixoY)
                            .addComponent(jCSegundo)
                            .addComponent(jCTerceiro)
                            .addComponent(jCPrimeiro)
                            .addComponent(jCQuarto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnLimpar)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(btnAvaliar)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jCEixoX)
                .addGap(18, 18, 18)
                .addComponent(jCEixoY)
                .addGap(18, 18, 18)
                .addComponent(jCPrimeiro)
                .addGap(18, 18, 18)
                .addComponent(jCSegundo)
                .addGap(18, 18, 18)
                .addComponent(jCTerceiro)
                .addGap(18, 18, 18)
                .addComponent(jCQuarto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnLimpar)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSegundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCSegundoActionPerformed

    private void jCPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPrimeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCPrimeiroActionPerformed

    private void jCTerceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTerceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTerceiroActionPerformed

    private void jCQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCQuartoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        jTX.setText("");
        jTY.setText("");
        jCEixoX.setSelected(false);
        jCEixoY.setSelected(false);
        jCPrimeiro.setSelected(false);
        jCSegundo.setSelected(false);
        jCTerceiro.setSelected(false);
        jCQuarto.setSelected(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed
        // TODO add your handling code here:
        try {
            int x = Integer.parseInt(jTX.getText());
            int y = Integer.parseInt(jTY.getText());
            Ponto p = new Ponto(x, y);
            btnLimparActionPerformed(evt);
            if (p.estaIncidindoSobreX()) {
                jCEixoX.setSelected(true);
            }

            if (p.estaIncidindoSobreY()) {
                jCEixoY.setSelected(true);
            }

            Quadrante quadrante = p.identificarQuadrante();
            if (quadrante == Quadrante.PRIMEIRO) {
                jCPrimeiro.setSelected(true);
            } else if (quadrante == Quadrante.SEGUNDO) {
                jCSegundo.setSelected(true);
            } else if (quadrante == Quadrante.TERCEIRO) {
                jCTerceiro.setSelected(true);
            } else if (quadrante == Quadrante.QUARTO) {
                jCQuarto.setSelected(true);
            }
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Erro: apenas números inteiros são aceitos.");
        }
    }//GEN-LAST:event_btnAvaliarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JCheckBox jCEixoX;
    private javax.swing.JCheckBox jCEixoY;
    private javax.swing.JCheckBox jCPrimeiro;
    private javax.swing.JCheckBox jCQuarto;
    private javax.swing.JCheckBox jCSegundo;
    private javax.swing.JCheckBox jCTerceiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTX;
    private javax.swing.JTextField jTY;
    // End of variables declaration//GEN-END:variables
}
