package Q2.View;

import Q2.Model.Empresa;
import Q2.Model.Funcionario;
import Q2.Model.Programador;
import Q2.Model.Venda;
import Q2.Model.Vendedor;
import javax.swing.JOptionPane;

/**
 *
 * @author Laura Möller
 */
public class Tela extends javax.swing.JFrame {

    private Empresa supreme;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        supreme = new Empresa("Supreme");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBCadastrarProgramador = new javax.swing.JButton();
        jBCadastrarVendedor = new javax.swing.JButton();
        jBCadastrarFuncionario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTNomeFuncionarioRemover = new javax.swing.JTextField();
        jBRemoverFuncionario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLCustosSalarios = new javax.swing.JLabel();
        jBCalcularCustos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBAlterarPercentualComissao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTNomeFuncionarioOpVendedores = new javax.swing.JTextField();
        jBVerificarPercentualComissao = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTNomeFuncionarioOpProgramadores = new javax.swing.JTextField();
        jBCadastrarLinguagem = new javax.swing.JButton();
        jBRemoverLinguagem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTNomeVerificarSalario = new javax.swing.JTextField();
        jBVerificarSalario = new javax.swing.JButton();
        jLSalario = new javax.swing.JLabel();
        jBAdicionarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Gerenciamento de Funcionarios da Empresa Supreme");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Remover Funcionário");

        jBCadastrarProgramador.setText("Programador");
        jBCadastrarProgramador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarProgramadorActionPerformed(evt);
            }
        });

        jBCadastrarVendedor.setText("Vendedor");
        jBCadastrarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarVendedorActionPerformed(evt);
            }
        });

        jBCadastrarFuncionario.setText("Funcionário Padrão");
        jBCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarFuncionarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Cadastrar Funcionário");

        jBRemoverFuncionario.setText("Remover");
        jBRemoverFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverFuncionarioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Calcular Custos com Salários");

        jLCustosSalarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLCustosSalarios.setText("R$");

        jBCalcularCustos.setText("Calcular");
        jBCalcularCustos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularCustosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Operações para Funcionários Vendedores");

        jBAlterarPercentualComissao.setText("Alterar Percentual de Comissão");
        jBAlterarPercentualComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarPercentualComissaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nome do Funcionário:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nome do Funcionário:");

        jBVerificarPercentualComissao.setText("Verificar Percentual de Comissão");
        jBVerificarPercentualComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificarPercentualComissaoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Operações para Funcionários Programadores");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nome do Funcionário:");

        jBCadastrarLinguagem.setText("Cadastrar Linguagem de Programação");
        jBCadastrarLinguagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarLinguagemActionPerformed(evt);
            }
        });

        jBRemoverLinguagem.setText("Remover Linguagem de Programação");
        jBRemoverLinguagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverLinguagemActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Verificar Salário de Um Funcionário");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Nome do Funcionário:");

        jBVerificarSalario.setText("Verificar Salário");
        jBVerificarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificarSalarioActionPerformed(evt);
            }
        });

        jLSalario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLSalario.setText("R$");

        jBAdicionarVenda.setText("Adicionar Venda");
        jBAdicionarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jBCadastrarProgramador)
                        .addGap(18, 18, 18)
                        .addComponent(jBCadastrarVendedor)
                        .addGap(18, 18, 18)
                        .addComponent(jBCadastrarFuncionario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBAlterarPercentualComissao)
                                .addGap(18, 18, 18)
                                .addComponent(jBVerificarPercentualComissao)
                                .addGap(18, 18, 18)
                                .addComponent(jBAdicionarVenda))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTNomeFuncionarioOpVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTNomeFuncionarioRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTNomeFuncionarioOpProgramadores, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jBRemoverFuncionario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBCadastrarLinguagem)
                                .addGap(18, 18, 18)
                                .addComponent(jBRemoverLinguagem)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLCustosSalarios)
                                        .addGap(280, 280, 280)
                                        .addComponent(jBCalcularCustos))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLSalario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jTNomeVerificarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jBVerificarSalario)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarProgramador)
                    .addComponent(jBCadastrarVendedor)
                    .addComponent(jBCadastrarFuncionario))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNomeFuncionarioRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRemoverFuncionario)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCustosSalarios)
                    .addComponent(jBCalcularCustos))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTNomeFuncionarioOpVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAlterarPercentualComissao)
                    .addComponent(jBVerificarPercentualComissao)
                    .addComponent(jBAdicionarVenda))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTNomeFuncionarioOpProgramadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBRemoverLinguagem)
                    .addComponent(jBCadastrarLinguagem))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTNomeVerificarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVerificarSalario))
                .addGap(18, 18, 18)
                .addComponent(jLSalario)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRemoverFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverFuncionarioActionPerformed
        // TODO add your handling code here:
        try {
            Funcionario f = supreme.procurarFuncionario(jTNomeFuncionarioRemover.getText());
            supreme.removerFuncionario(f);
            JOptionPane.showMessageDialog(this, "Funcionário Removido.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jTNomeFuncionarioRemover.setText("");
    }//GEN-LAST:event_jBRemoverFuncionarioActionPerformed

    private void jBCalcularCustosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularCustosActionPerformed
        // TODO add your handling code here:
        try {
            jLCustosSalarios.setText("R$" + supreme.calcularCustosSalarios());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jBCalcularCustosActionPerformed

    private void jBAlterarPercentualComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarPercentualComissaoActionPerformed
        // TODO add your handling code here:
        try {
            Vendedor v = (Vendedor) supreme.procurarFuncionario(jTNomeFuncionarioOpVendedores.getText());
            if (v == null) {
                JOptionPane.showMessageDialog(this, "Funcionário não encontrado!");
                return;
            }
            double percentual = Double.parseDouble(JOptionPane.showInputDialog(this, "Insira o novo percentual:"));
            v.setPercentualComissao(percentual);
            JOptionPane.showMessageDialog(this, "Percentual de Comissão Alterado.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jTNomeFuncionarioOpVendedores.setText("");
    }//GEN-LAST:event_jBAlterarPercentualComissaoActionPerformed

    private void jBVerificarPercentualComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificarPercentualComissaoActionPerformed
        // TODO add your handling code here:
        try {
            Vendedor v = (Vendedor) supreme.procurarFuncionario(jTNomeFuncionarioOpVendedores.getText());
            if (v == null) {
                JOptionPane.showMessageDialog(this, "Funcionário não encontrado!");
                return;
            }
            JOptionPane.showMessageDialog(this, "Percentual de Comissão: " + v.getPercentualComissao());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jTNomeFuncionarioOpVendedores.setText("");
    }//GEN-LAST:event_jBVerificarPercentualComissaoActionPerformed

    private void jBCadastrarLinguagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarLinguagemActionPerformed
        // TODO add your handling code here:
        try {
            String nome = jTNomeFuncionarioOpProgramadores.getText();
            Funcionario f = supreme.procurarFuncionario(nome);

            if (f instanceof Programador) {
                Programador p = (Programador) f; // Cast seguro
                p.incluirLinguagem(JOptionPane.showInputDialog(this, "Linguagem que deseja adicionar"));
                JOptionPane.showMessageDialog(this, "Linguagem adicionada!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro: Este funcionário não é um Programador.");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jTNomeFuncionarioOpProgramadores.setText("");

    }//GEN-LAST:event_jBCadastrarLinguagemActionPerformed

    private void jBRemoverLinguagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverLinguagemActionPerformed
        // TODO add your handling code here:
        try {
            Programador p = (Programador) supreme.procurarFuncionario(jTNomeFuncionarioOpProgramadores.getText());
            if (p == null) {
                JOptionPane.showMessageDialog(this, "Funcionário não encontrado!");
                return;
            }
            p.removerLinguagem(JOptionPane.showInputDialog(this, "Digite a linguagem de programação que deseja remover: "));
            JOptionPane.showMessageDialog(this, "Linguagem removida.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jTNomeFuncionarioOpProgramadores.setText("");
    }//GEN-LAST:event_jBRemoverLinguagemActionPerformed

    private void jBVerificarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificarSalarioActionPerformed
        // TODO add your handling code here:
        try {
            Funcionario f = supreme.procurarFuncionario(jTNomeVerificarSalario.getText());
            if (f == null) {
                JOptionPane.showMessageDialog(this, "Funcionário não encontrado!");
                return;
            }
            jLSalario.setText("R$" + f.calcularSalario());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jTNomeVerificarSalario.setText("");
    }//GEN-LAST:event_jBVerificarSalarioActionPerformed

    private void jBCadastrarProgramadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarProgramadorActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarProgramador(supreme).setVisible(true);
    }//GEN-LAST:event_jBCadastrarProgramadorActionPerformed

    private void jBCadastrarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarVendedorActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarVendedor(supreme).setVisible(true);
    }//GEN-LAST:event_jBCadastrarVendedorActionPerformed

    private void jBCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarFuncionario(supreme).setVisible(true);
    }//GEN-LAST:event_jBCadastrarFuncionarioActionPerformed

    private void jBAdicionarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarVendaActionPerformed
        // TODO add your handling code here:
        try {
            String nome = jTNomeFuncionarioOpVendedores.getText();
            Funcionario f = supreme.procurarFuncionario(nome);

            if (f instanceof Vendedor) {
                Vendedor v = (Vendedor) f;
                double valorVenda = Double.parseDouble(JOptionPane.showInputDialog(this, "Valor da venda: "));
                v.incluirVenda(new Venda(valorVenda));
                JOptionPane.showMessageDialog(this, "Venda adicionada!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro: Este funcionário não é um Vendedor.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: formato numérico.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jTNomeFuncionarioOpVendedores.setText("");
    }//GEN-LAST:event_jBAdicionarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionarVenda;
    private javax.swing.JButton jBAlterarPercentualComissao;
    private javax.swing.JButton jBCadastrarFuncionario;
    private javax.swing.JButton jBCadastrarLinguagem;
    private javax.swing.JButton jBCadastrarProgramador;
    private javax.swing.JButton jBCadastrarVendedor;
    private javax.swing.JButton jBCalcularCustos;
    private javax.swing.JButton jBRemoverFuncionario;
    private javax.swing.JButton jBRemoverLinguagem;
    private javax.swing.JButton jBVerificarPercentualComissao;
    private javax.swing.JButton jBVerificarSalario;
    private javax.swing.JLabel jLCustosSalarios;
    private javax.swing.JLabel jLSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTNomeFuncionarioOpProgramadores;
    private javax.swing.JTextField jTNomeFuncionarioOpVendedores;
    private javax.swing.JTextField jTNomeFuncionarioRemover;
    private javax.swing.JTextField jTNomeVerificarSalario;
    // End of variables declaration//GEN-END:variables
}
