/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Produto;
import Model.ProdutosCadastrados;
import javax.swing.JOptionPane;

/**
 *
 * @author Laura Möller
 */
public class TelaProdutos extends javax.swing.JFrame {

    private ProdutosCadastrados produtosCadastrados;

    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutos(ProdutosCadastrados produtosCadastrados) {
        initComponents();
        this.produtosCadastrados = produtosCadastrados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTValorUnitario = new javax.swing.JTextField();
        jBCadastrarProduto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTPesquisaNome = new javax.swing.JTextField();
        jTPesquisaNumero = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jBRemoverProduto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTAlterarNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTAlterarNumero = new javax.swing.JTextField();
        jBAlterarNome = new javax.swing.JButton();
        jBAlterarValor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Alterar Valor Unitário ou Nome de Um Produto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Digite o nome do produto que deseja cadastrar:");

        jTNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeProdutoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Digite o valor unitário do produto:");

        jBCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBCadastrarProduto.setText("Cadastrar");
        jBCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarProdutoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Cadastrar Produtos");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Existem três maneiras de realizar essas operações: informando o número de cadastro e o nome; informando apenas o número de cadastro; ou informando apenas o nome do produto. Após isso, clique no botão referente a ação desejada.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Número:");

        jBPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBPesquisar.setText("Pesquisar Produto");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBRemoverProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBRemoverProduto.setText("Remover Produto");
        jBRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverProdutoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("Verificar Cadastro de Um Produto / Remover Produto");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nome:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Número:");

        jBAlterarNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBAlterarNome.setText("Alterar Nome do Produto");
        jBAlterarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarNomeActionPerformed(evt);
            }
        });

        jBAlterarValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBAlterarValor.setText("Alterar Valor Unitário do Produto");
        jBAlterarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(82, 82, 82)
                                    .addComponent(jTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(75, 75, 75)
                            .addComponent(jBCadastrarProduto))
                        .addComponent(jSeparator2))
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBRemoverProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jTPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(82, 82, 82)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jTPesquisaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)
                            .addComponent(jBPesquisar)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTAlterarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAlterarValor)
                            .addComponent(jBAlterarNome))))
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel4)
                    .addContainerGap(581, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jBCadastrarProduto)))
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTPesquisaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBPesquisar)))
                .addGap(18, 18, 18)
                .addComponent(jBRemoverProduto)
                .addGap(32, 32, 32)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTAlterarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBAlterarNome)))
                .addGap(18, 18, 18)
                .addComponent(jBAlterarValor)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel4)
                    .addContainerGap(709, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeProdutoActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
        try {
            String num = jTPesquisaNumero.getText();
            String nome = jTPesquisaNome.getText();

            Produto p = criarObjeto(nome, num);

            Produto prodCadastrado = produtosCadastrados.verificarProdutoCadastrado(p);

            if (prodCadastrado == null) {
                JOptionPane.showMessageDialog(this, "O produto não foi localizado.");
            } else {
                JOptionPane.showMessageDialog(this, "Produto Localizado!\n" + prodCadastrado.getNomeProduto() + " - R$" + prodCadastrado.getValor() + " - " + prodCadastrado.getNumProduto());
            }

            jTValorUnitario.setText("");
            jTNomeProduto.setText("");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            jTValorUnitario.setText("");
            jTNomeProduto.setText("");
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        try {
            String textoValor = jTValorUnitario.getText();
            String nome = jTNomeProduto.getText();

            if (textoValor.isBlank()) {
                throw new IllegalArgumentException("Erro: O campo de valor unitário não pode estar vazio.");
            }

            double valor;
            try {
                valor = Double.parseDouble(textoValor.replace(",", "."));
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Erro: O valor deve ser um número válido (ex: 10.50).");
            }

            Produto p = new Produto(nome, valor);
            produtosCadastrados.adicionarProduto(p);
            jTValorUnitario.setText("");
            jTNomeProduto.setText("");
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso.");
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Erro: O valor deve ser um número válido (ex: 10.50).");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jBCadastrarProdutoActionPerformed

    private void jBRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverProdutoActionPerformed
        // TODO add your handling code here:
        try {
            String num = jTPesquisaNumero.getText();
            String nome = jTPesquisaNome.getText();

            Produto p = criarObjeto(nome, num);

            produtosCadastrados.removerProduto(p);
            JOptionPane.showMessageDialog(this, "Produto removido com sucesso!");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        jTPesquisaNumero.setText("");
        jTPesquisaNome.setText("");

    }//GEN-LAST:event_jBRemoverProdutoActionPerformed

    private void jBAlterarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarNomeActionPerformed
        // TODO add your handling code here:
        try {
            String nomeOriginal = jTAlterarNome.getText();
            String numStr = jTAlterarNumero.getText();

            Produto pBusca = criarObjeto(nomeOriginal, numStr);
            produtosCadastrados.alterarNomeDeProduto(pBusca);

            jTAlterarNome.setText("");
            jTAlterarNumero.setText("");

            JOptionPane.showMessageDialog(this, "Nome do Produto alterado com sucesso!");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            jTAlterarNome.setText("");
            jTAlterarNumero.setText("");
        }
    }//GEN-LAST:event_jBAlterarNomeActionPerformed

    private void jBAlterarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarValorActionPerformed
        // TODO add your handling code here:
        try {
            String nome = jTAlterarNome.getText();
            String numStr = jTAlterarNumero.getText();

            Produto pBusca = criarObjeto(nome, numStr);
            produtosCadastrados.alterarValorDeProduto(pBusca);

            jTAlterarNome.setText("");
            jTAlterarNumero.setText("");

            JOptionPane.showMessageDialog(this, "Valor do Produto alterado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            jTAlterarNome.setText("");
            jTAlterarNumero.setText("");
        }
    }//GEN-LAST:event_jBAlterarValorActionPerformed

    public Produto criarObjeto(String nome, String numero) {

        try {
            if (numero.isBlank() && nome.isBlank()) {
                JOptionPane.showMessageDialog(this, "É preciso informar ao menos o nome ou o número do produto.");
                return null;
            }

            int num = 0;
            if (!numero.isBlank()) {
                num = Integer.parseInt(numero);
            }

            if (nome.isBlank()) {
                return new Produto(num);
            }

            return new Produto(nome, num);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: formato númerico.");
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterarNome;
    private javax.swing.JButton jBAlterarValor;
    private javax.swing.JButton jBCadastrarProduto;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBRemoverProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTAlterarNome;
    private javax.swing.JTextField jTAlterarNumero;
    private javax.swing.JTextField jTNomeProduto;
    private javax.swing.JTextField jTPesquisaNome;
    private javax.swing.JTextField jTPesquisaNumero;
    private javax.swing.JTextField jTValorUnitario;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
