/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Comanda;
import Model.GerenciadorComandas;
import Model.ItemComanda;
import Model.ProdutosCadastrados;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Laura Möller
 */
public class TelaGerenciarComandas extends javax.swing.JFrame {

    private ProdutosCadastrados produtosCadastrados = new ProdutosCadastrados();
    private GerenciadorComandas gerenciadorComandas = new GerenciadorComandas();

    /**
     * Creates new form TelaGerenciarComandas
     */
    public TelaGerenciarComandas(ProdutosCadastrados produtosCadastrados, GerenciadorComandas gerenciadorComandas) {
        initComponents();
        this.produtosCadastrados = produtosCadastrados;
        this.gerenciadorComandas = gerenciadorComandas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBAbrirComanda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jBFecharComanda = new javax.swing.JButton();
        jTNumeroComanda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBChecarItens = new javax.swing.JButton();
        jBAdicionarItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Ações na Comanda");

        jBAbrirComanda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBAbrirComanda.setText("Clique Para Abrir Uma Nova Comanda");
        jBAbrirComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirComandaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Abrir Comanda");

        jBFecharComanda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBFecharComanda.setText("Clique Para Fechar a Comanda");
        jBFecharComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharComandaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Número da Comanda:");

        jBChecarItens.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBChecarItens.setText("Clique Para Checar Itens da Comanda");
        jBChecarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChecarItensActionPerformed(evt);
            }
        });

        jBAdicionarItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBAdicionarItem.setText("Clique Para Adicionar Item");
        jBAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAbrirComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBFecharComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167)
                                .addComponent(jBChecarItens, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(61, 61, 61)
                                .addComponent(jTNumeroComanda))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jBAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBAbrirComanda)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNumeroComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBChecarItens)
                    .addComponent(jBFecharComanda))
                .addGap(69, 69, 69)
                .addComponent(jBAdicionarItem)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAbrirComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirComandaActionPerformed
        // TODO add your handling code here:
        try {
            Comanda comanda = gerenciadorComandas.abrirComanda();
            JOptionPane.showMessageDialog(this, "Comanda nº" + comanda.getNumeroComanda() + " foi aberta.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Erro: não foi possível abrir comanda.");
        }
    }//GEN-LAST:event_jBAbrirComandaActionPerformed

    private void jBFecharComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharComandaActionPerformed
        // TODO add your handling code here:
        try {
            if (jTNumeroComanda.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Preencha o campos!");
                return;
            }
            int numComanda = Integer.parseInt(jTNumeroComanda.getText());
            gerenciadorComandas.fecharComanda(numComanda);
            JOptionPane.showMessageDialog(this, "Comanda de nº" + numComanda + " foi fechada");
            jTNumeroComanda.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: formato númerico.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jBFecharComandaActionPerformed

    private void jBChecarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChecarItensActionPerformed
        // TODO add your handling code here:
        try {
            if (jTNumeroComanda.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Preencha o campos!");
                return;
            }
            int numComanda = Integer.parseInt(jTNumeroComanda.getText());
            Comanda comanda = gerenciadorComandas.buscarComanda(numComanda);
            if (comanda == null) {
                JOptionPane.showMessageDialog(this, "Erro: comanda de nº" + numComanda + " não encontrada.");
                return;
            }
            String lista = comanda.listaDeProdutos();
            JOptionPane.showMessageDialog(this, lista);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: formato númerico.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jBChecarItensActionPerformed

    private void jBAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarItemActionPerformed
        // TODO add your handling code here:
        try {
            if (jTNumeroComanda.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Preencha o campos!");
                return;
            }
            int numComanda = Integer.parseInt(jTNumeroComanda.getText());
            Comanda comanda = gerenciadorComandas.buscarComanda(numComanda);

            if (comanda == null) {
                JOptionPane.showMessageDialog(this, "Erro: Comanda " + numComanda + " não encontrada.");
                return;
            }

            new AdicionarItemComanda(produtosCadastrados, gerenciadorComandas, comanda).setVisible(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: formato númerico.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jBAdicionarItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAbrirComanda;
    private javax.swing.JButton jBAdicionarItem;
    private javax.swing.JButton jBChecarItens;
    private javax.swing.JButton jBFecharComanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTNumeroComanda;
    // End of variables declaration//GEN-END:variables
}
